<?php
$a = intval("1.5");
$b = (double)"1.5";
echo $a + $b;


'bell.jpg',
    'women.jpg',
    'watermelon.jpg',
    'wild.jpg',
    'strickwild.jpg',
    'ring.jpg',
    'Wristwatch.jpg',
    'glass.jpg'



    '<img src = img/wild.jpg><img src = img/wild.jpg><img src = img/wild.jpg>' => '5',
    '<img src = img/women.jpg><img src = img/women.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/watermelon.jpg><img src = img/watermelon.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/bell.jpg><img src = img/bell.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/strickwild.jpg><img src = img/strickwild.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/seven.jpg><img src = img/seven.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/ring.jpg><img src = img/ring.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/Wristwatch.jpg><img src = img/Wristwatch.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/glass.jpg><img src = img/glass.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/women.jpg><img src = img/bell.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/bell.jpg><img src = img/women.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/watermelon.jpg><img src = img/bell.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/bell.jpg><img src = img/watermelon.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/strickwild.jpg><img src = img/bell.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/bell.jpg><img src = img/strickwild.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/seven.jpg><img src = img/bell.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/bell.jpg><img src = img/seven.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/ring.jpg><img src = img/bell.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/bell.jpg><img src = img/ring.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/Wristwatch.jpg><img src = img/bell.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/bell.jpg><img src = img/Wristwatch.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/glass.jpg><img src = img/bell.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/bell.jpg><img src = img/glass.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/watermelon.jpg><img src = img/women.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/women.jpg><img src = img/watermelon.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/strickwild.jpg><img src = img/women.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/women.jpg><img src = img/strickwild.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/seven.jpg><img src = img/women.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/women.jpg><img src = img/seven.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/ring.jpg><img src = img/women.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/women.jpg><img src = img/wing.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/Wristwatch.jpg><img src = img/women.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/women.jpg><img src = img/Wristwatch.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/glass.jpg><img src = img/women.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/women.jpg><img src = img/glass.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/strickwild.jpg><img src = img/watermelon.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/watermelon.jpg><img src = img/strickwild.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/seven.jpg><img src = img/watermelon.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/watermelon.jpg><img src = img/seven.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/ring.jpg><img src = img/watermelon.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/watermelon.jpg><img src = img/ring.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/Wristwatch.jpg><img src = img/watermelon.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/watermelon.jpg><img src = img/Wristwatch.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/glass.jpg><img src = img/watermelon.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/watermelon.jpg><img src = img/glass.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/seven.jpg><img src = img/strickwild.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/strickwild.jpg><img src = img/seven.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/ring.jpg><img src = img/strickwild.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/strickwild.jpg><img src = img/ring.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/Wristwatch.jpg><img src = img/strickwild.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/strickwild.jpg><img src = img/Wristwatch.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/glass.jpg><img src = img/strickwild.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/strickwild.jpg><img src = img/glass.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/ring.jpg><img src = img/seven.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/seven.jpg><img src = img/ring.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/Wristwatch.jpg><img src = img/seven.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/seven.jpg><img src = img/Wristwatch.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/glass.jpg><img src = img/seven.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/seven.jpg><img src = img/glass.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/wild.jpg><img src = img/glass.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/wild.jpg><img src = img/Wristwatch.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/wild.jpg><img src = img/ring.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/wild.jpg><img src = img/seven.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/wild.jpg><img src = img/strickwild.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/wild.jpg><img src = img/watermelon.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/wild.jpg><img src = img/women.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/wild.jpg><img src = img/bell.jpg><img src = img/wild.jpg>' => '1',
    '<img src = img/women.jpg><img src = img/wild.jpg><img src = img/wild.jpg>' => '3',
    '<img src = img/watermelon.jpg><img src = img/wild.jpg><img src = img/wild.jpg>' => '3',
    '<img src = img/strickwild.jpg><img src = img/wild.jpg><img src = img/wild.jpg>' => '3',
    '<img src = img/seven.jpg><img src = img/wild.jpg><img src = img/wild.jpg>' => '3',
    '<img src = img/ring.jpg><img src = img/wild.jpg><img src = img/wild.jpg>' => '3',
    '<img src = img/Wristwatch.jpg><img src = img/wild.jpg><img src = img/wild.jpg>' => '3',
    '<img src = img/glass.jpg><img src = img/wild.jpg><img src = img/wild.jpg>' => '3',
    '<img src = img/strickwild.jpg><img src = img/strickwild.jpg><img src = img/strickwild.jpg>' => '30',